import { useState, useEffect } from 'react';

// Define the type of our server data here as there is no other types
export interface ServerData {
  name: string;
  description: string;
  url: string;
  stars: number;
  lastUpdated: string; // ISO String
}

export function useRegistryData() {
  const [servers, setServers] = useState<ServerData[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [lastUpdated, setLastUpdated] = useState<Date | null>(null);

  useEffect(() => {
    async function fetchData() {
      try {
        setLoading(true);
        setError(null);
        // We will fetch the local artifact generated by the pipeline
        const response = await fetch('/data.json');

        if (!response.ok) {
          throw new Error(`Failed to fetch data: ${response.statusText}`);
        }

        const data = await response.json();
        setServers(data.servers || []);

        // Use the artifact's generation time or fallback to now
        if (data.lastUpdated) {
          setLastUpdated(new Date(data.lastUpdated));
        } else {
          setLastUpdated(new Date());
        }

      } catch (err) {
        console.error('Error loading registry data:', err);
        setError(err instanceof Error ? err.message : 'Unknown error occurred');
        // Load mock data on error so the UI still works?
        // Or keep servers empty as it gracefully handles it
      } finally {
        setLoading(false);
      }
    }

    fetchData();
  }, []);

  return { servers, loading, error, lastUpdated };
}
